### ISSUE TITLE
Composer installable

### ISSUE THREAD

**Issue by reyostallenberg** [dsmink/twig-bulma-form-theme-bundle#2]
Can we make this repo composer installable? It would ease the installation and usage very much

**Comment by dsmink** [comment]
Sure. I think that is a good idea!

**Comment by reyostallenberg** [comment]
Also I think it could better be a bundle (so that needs a name change of the repo in my opinion)
When it's a composer installable bundle many stuff can work out-of-the-box instead of having to copy examples.

I don't have a need anymore for al this to happen, but I'm willing to help if you want.

**Comment by dsmink** [comment]
@reyostallenberg That would be appreciated!

**Comment by reyostallenberg** [comment]
So you are firstly renaming the repo to
'dsmink/twig-bulma-form-theme-bundle'?

**Comment by reyostallenberg** [comment]
Closing because #7 is merged
